- .travis.yml
- README.md
- composer.json
- dev/docker/Dockerfile
- docker-compose.yml
- docs/index.md
- phpunit.xml.dist
- src/Resources/config/storage/doctrine.xml
- tests/Acceptance/AuthorizationEndpointTest.php
- tests/Acceptance/ClearExpiredTokensCommandTest.php
- tests/Acceptance/DoctrineAccessTokenManagerTest.php
- tests/Acceptance/DoctrineAuthCodeManagerTest.php
- tests/Acceptance/DoctrineRefreshTokenManagerTest.php
- tests/Acceptance/TokenEndpointTest.php
- tests/Fixtures/routes.yaml
- tests/Integration/AuthorizationServerTest.php
- tests/TestKernel.php
- tests/Unit/InMemoryAccessTokenManagerTest.php
- tests/Unit/InMemoryAuthCodeManagerTest.php
- tests/Unit/InMemoryRefreshTokenManagerTest.php
- Removes the ext-timecop dev dependency
- Stop using MicroKernelTrait to avoid the need for forward compatibility layers in test classes
> Simpify test suite

- README.md
- composer.json
- src/Controller/AuthorizationController.php
- src/Controller/TokenController.php
- src/DependencyInjection/LeagueOAuth2ServerExtension.php
- src/Resources/config/services.xml
- tests/TestKernel.php
- Drop SensioFrameworkExtraBundle dependency
- Don't abstract anymore the PSR7/17 implementation and require `nyholm/psr7` implementation. Therefore drop `laminas/laminas-diactoros` implementation in tests
- Fix test kernel location (`Tests -> tests`)
> Drop SensioFrameworkExtraBundle dependency

- psalm.xml
- src/Command/CreateClientCommand.php
- src/League/Entity/Client.php
- src/League/Repository/ClientRepository.php
- src/Model/Client.php
- src/Resources/config/doctrine/model/Client.orm.xml
- tests/Acceptance/CreateClientCommandTest.php
- tests/Acceptance/DeleteClientCommandTest.php
- tests/Acceptance/DoctrineAccessTokenManagerTest.php
- tests/Acceptance/DoctrineAuthCodeManagerTest.php
- tests/Acceptance/DoctrineClientManagerTest.php
- tests/Acceptance/DoctrineCredentialsRevokerTest.php
- tests/Acceptance/DoctrineRefreshTokenManagerTest.php
- tests/Acceptance/ListClientsCommandTest.php
- tests/Acceptance/UpdateClientCommandTest.php
- tests/Fixtures/FixtureFactory.php
- tests/Integration/AuthCodeRepositoryTest.php
- tests/Unit/ClientEntityTest.php
- tests/Unit/InMemoryAccessTokenManagerTest.php
- tests/Unit/InMemoryAuthCodeManagerTest.php
- tests/Unit/InMemoryRefreshTokenManagerTest.php
fixes: https://github.com/trikoder/oauth2-bundle/issues/209 / https://github.com/trikoder/oauth2-bundle/issues/145
`league/oauth2-server` uses both `name` and `identifier`, so it makes sense to do the same here.
"name" doesn't have to be unique, it's the name of the oauth client which might be used at the user consent page so the user knows which application they are logging into.
> add support for client name

- docs/controlling-token-scopes.md
- docs/implementing-custom-grant-type.md
- psalm.xml
- src/DependencyInjection/LeagueOAuth2ServerExtension.php
- src/LeagueOAuth2ServerBundle.php
- src/OAuth2Events.php
- src/Resources/config/routes.php
- src/Resources/config/services.php
- src/Resources/config/storage/doctrine.php
- src/Resources/config/storage/in_memory.php
- tests/Acceptance/TokenEndpointTest.php
- tests/Integration/AuthorizationServerTest.php
- tests/TestKernel.php
- tests/Unit/ExtensionTest.php
- Added bundle friendly aliases for services
- Changed alias namespace from `league.oauth2-server` to `league.oauth2_server`
- Changed psr7/17 definition ids: from FQCN to ids (which prevent unexpected behaviors if these ids are defined in the userland)
> Add "bundle friendly" aliases

- docs/basic-setup.md
- src/Command/UpdateClientCommand.php
- tests/Acceptance/UpdateClientCommandTest.php
The previous command used to use the "set" way to deal with relationships.
As an example, `--scope` option was used to define every scope that will be linked to a client.
This meant that if the `--scope` option was not provided, the command thought that `[]` was the wanted scopes.
The new approach is to use the "add/remove" way instead.
I also added the possibility to activate a client (before we only could deactivate it)
So here is the new command behavior:
```
Description:
Updates an oAuth2 client
Usage:
league:oauth2-server:update-client [options] [--] <identifier>
Arguments:
identifier                                     The client identifier
Options:
--add-redirect-uri=ADD-REDIRECT-URI        Add allowed redirect uri to the client. (multiple values allowed) …
```
> Improve update command

- src/Security/Authenticator/OAuth2Authenticator.php
- tests/Acceptance/SecurityLayerTest.php
- tests/Fixtures/SecurityTestController.php
- tests/Integration/AuthorizationServerTest.php
This fixes the problem that the client receives a `The resource server rejected the request.` when it tries to access a public endpoint (reported by #42).
Also potentially fixes conflicts when multiple authenticators are configured.
> OAuth2Authenticator should only support Bearer authorizations

- docs/using-custom-client.md
- src/DependencyInjection/LeagueOAuth2ServerExtension.php
- src/Model/AbstractClient.php
- src/Persistence/Mapping/Driver.php
This is a fix for bug #45.
Turns out that AbstractClient is wrongly mapped.
Quoted from [Doctrine/ORM documentation](https://github.com/thephpleague/oauth2-server-bundle/compare/master...yoshz:bugfix/docrine-mapping):
> A mapped superclass cannot be an entity, it is not query-able and persistent relationships defined by a mapped superclass must be unidirectional (with an owning side only). This means that One-To-Many associations are not possible on a mapped superclass at all. Furthermore Many-To-Many associations are only possible if the mapped superclass is only used in exactly one entity at the moment. For further support of inheritance, the single or joined table inheritance features have to be used.
So AbstractClient can not have an identifier and can not be used as an association …
> SuperClass AbstractClient can not have indentifier mapped

- src/Controller/TokenController.php
- src/Event/TokenRequestResolveEvent.php
- src/OAuth2Events.php
- src/Resources/config/services.php
- tests/Acceptance/TokenEndpointTest.php
I've added an event to manipulate the response during /token process. Useful to add some Set-Cookie directives for example.
> add request token event

- src/DependencyInjection/Security/OAuth2Factory.php
- src/Resources/config/services.php
- tests/TestKernel.php
> Fix authenticator registration with multiple user providers

- src/Security/Authentication/Token/OAuth2Token.php
- src/Security/Authenticator/OAuth2Authenticator.php
- tests/Unit/OAuth2AuthenticatorTest.php
- tests/Unit/OAuth2TokenTest.php
This PR should help with issue #50. It adds Client ID to the Passport and Token.
This way the client can be retrieved like this:
```
$clientId = $this->security->getToken()->getOAuthClientId();
$userRepository->findOneByClientId($clientId);
```
> Add OAuth Client ID to OAuth2Token

- .github/workflows/coding-standards.yml
- .github/workflows/static-analysis.yml
- .github/workflows/unit-tests.yml
- CONTRIBUTING.md
- composer.json
- dev/bin/php-debug
- dev/bin/php-test
- dev/docker/Dockerfile
- dev/docker/entrypoint.sh
- docker-compose.yml
- src/Security/Authenticator/ForwardCompatAuthenticatorTrait.php
Alternative to #56 updating current docker environment.
Fix #55
> Update docker environment and CONTRIBUTING.md instructions

- docs/debugging.md
This PR updates the debugging docs to reflect that PHPUnit is no longer a `require-dev` dependency and that simple PHPUnit is used instead.
> Fix debugging docs

- .github/workflows/unit-tests.yml
- src/Security/Authenticator/OAuth2Authenticator.php
After upgrading to symfony 5.4, authorization is broken because the OAuth2Token doesn't is "authenticated" anymore (see #68).
From symfony 5.4 on the `authenticated` property is not used anymore but triggers an error in the AuthorizationChecker when it is false (this seems buggy as well).
This fix ensures the authenticated property is always true when an user is set on the token.
~~This is the same behavior as the UsernamePasswordToken and RememberMeToken.~~
Seems this fix is only necessary for symfony 5.4. Symfony 6.0 works fine.
I have updated the pipeline config to tests on the right versions and update composer to v2 as it is required for symfony 6.0.
> Make sure token is always authenticated

- tests/Acceptance/SecurityLayerTest.php
- tests/Fixtures/SecurityTestController.php
- tests/Fixtures/routes.php
This PR adds a regression test which was previously missing (it checks that the bundle integrates properly with Symfony authorization).
This test is failing on Symfony 5.4 without the changes that were made in https://github.com/thephpleague/oauth2-server-bundle/pull/72 so it's needed to prove that the bundle works as intended after that change was made.
> Add authorization tests

- docs/index.md
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/LeagueOAuth2ServerExtension.php
- src/Manager/InMemory/AccessTokenManager.php
- src/Manager/Null/AccessTokenManager.php
- src/Persistence/Mapping/Driver.php
- src/Repository/NullAccessTokenRepository.php
- src/Resources/config/access_token/default.php
- src/Resources/config/access_token/null.php
- src/Resources/config/services.php
- src/Resources/config/storage/doctrine.php
- tests/Acceptance/DoctrineAccessTokenManagerTest.php
- tests/Integration/AbstractIntegrationTest.php
- tests/Unit/InMemoryAccessTokenManagerTest.php
@mtarld  @chalasr this is the port of disabled access token saving feature 😉
> add disable access token saving feature

- .github/workflows/unit-tests.yml
Update the tests matrix with the latest versions of PHP and Symfony
The PHP 8.1 docker image is not available yet and support of PHP 7.3 will be dropped in 6 days. I will update the PR and I will mark it as ready for review when this happens.
> Update test matrix

- docs/token-scopes.md
The event name for `league.oauth2_server.event.scope_resolve` is wrongly documented.
> Fixed wrong event name to league.oauth2_server.event.scope_resolve

- docs/index.md
- docs/password-grant-handling.md
Since the Password grant was reverted, a small example in the documentation was needed for this grant.
> Added password grant handling doc

- src/Command/ClearExpiredTokensCommand.php
- src/Command/CreateClientCommand.php
- src/Command/DeleteClientCommand.php
- src/Command/ListClientsCommand.php
- src/Command/UpdateClientCommand.php
- src/Resources/config/services.php
This PR a follow up of #105 and it's addressing the following deprecation warnings that I'm getting when using Symfony 6.1 and the latest version of the oauth2 server bundle.
```
2022-10-13T07:48:25+00:00 [info] User Deprecated: Since symfony/console 6.1: Relying on the static property "$defaultName" for setting a command name is deprecated. Add the "Symfony\Component\Console\Attribute\AsCommand" attribute to the "League\Bundle\OAuth2ServerBundle\Command\CreateClientCommand" class instead.
2022-10-13T07:48:25+00:00 [info] User Deprecated: Since symfony/console 6.1: Relying on the static property "$defaultName" for setting a command name is deprecated. Add the "Symfony\Component\Console\Attribute\AsCommand" attribute to the "League\Bundle\OAuth2ServerBundle\Command\UpdateClientCommand" …
```
> Fix deprecation warnings in commands

- src/DependencyInjection/CompilerPass/RegisterDoctrineOrmMappingPass.php
Registration of entity namespaces has been deprecated in doctrine/persistence 2.x and prevents usage of the bundle in combination with doctrine/persistence 3.x. This patch addresses #135
> Remove deprecated registration of entity namespace

- src/EventListener/AuthorizationRequestUserResolvingListener.php
- src/EventListener/AuthorizationRequestUserResolvingListenerTrait.php
- src/Resources/config/services.php
As the title states :) In Symfony 6.2 the Security helper of the Security component has been marked as deprecated, with a replacement helper being added in the Security bundle. This change fixes the deprecation by referencing the service by the name (`security.helper`) instead of the FQN, and for the "user" two implementations are added, one depending on the old class and one depending on the new class.
Tested on PHP 7.2 and 8.1 using both high and low dependencies.
> Fix Symfony 6.2 deprecation for Security helper

- docs/basic-setup.md
Fixes issue #80 
The default configured route is /token, this is the firewall exception for /api/token, which doesn't match.
> Update firewall config in basic-setup.md

- docs/index.md
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/LeagueOAuth2ServerExtension.php
- src/Persistence/Mapping/Driver.php
- src/Resources/config/storage/doctrine.php
I need to configure the table name in order to store oauth2  data in a custom PostgreSQL schema, so I'd like to have the option to configure the table name prefix.
What do you think?
> Allow custom table prefix

- src/Event/PreSaveClientEvent.php
- src/Manager/AccessTokenManagerInterface.php
- src/Manager/AuthorizationCodeManagerInterface.php
- src/Manager/ClientManagerInterface.php
- src/Manager/Doctrine/AccessTokenManager.php
- src/Manager/Doctrine/AuthorizationCodeManager.php
- src/Manager/Doctrine/ClientManager.php
- src/Manager/Doctrine/RefreshTokenManager.php
- src/Manager/InMemory/AccessTokenManager.php
- src/Manager/InMemory/AuthorizationCodeManager.php
- src/Manager/InMemory/ClientManager.php
- src/Manager/InMemory/RefreshTokenManager.php
- src/Manager/RefreshTokenManagerInterface.php
- src/Model/AbstractClient.php
- src/Model/AccessToken.php
- src/Model/AccessTokenInterface.php
- src/Model/AuthorizationCode.php
- src/Model/AuthorizationCodeInterface.php
- src/Model/ClientInterface.php
- src/Model/RefreshToken.php
- src/Model/RefreshTokenInterface.php
> Decoupled models from managers issue

- src/Model/RefreshToken.php
Too strict typehint prevents implementation of custom AccessToken model.
> Switch typehint strictness to use interface instead of implementation

- .github/workflows/coding-standards.yml
- .github/workflows/static-analysis.yml
- .github/workflows/unit-tests.yml
This allows to get rid of the following deprecations:
```
PHP 7.2 - Symfony 5.4.* - Composer --prefer-stable --prefer-lowest
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2.
```
> ci: Update actions/checkout version

- src/DependencyInjection/Configuration.php
- src/DependencyInjection/LeagueOAuth2ServerExtension.php
- src/Resources/config/services.php
> feat: config response type class

- docs/basic-setup.md
`name` is the first argument and is mandatory.
See
- `php bin/console help league:oauth2-server:create-client`
- [`CreateClientCommand::configure`](https://github.com/thephpleague/oauth2-server-bundle/blob/master/src/Command/CreateClientCommand.php#L79-L93)
> basic-setup.md: Add create-client's name arg

- .github/workflows/static-analysis.yml
- .github/workflows/unit-tests.yml
- composer.json
- src/Model/AbstractClient.php
- src/Model/RefreshToken.php
- src/Security/Authenticator/OAuth2Authenticator.php
- src/Security/Exception/InsufficientScopesException.php
- src/Security/Exception/OAuth2AuthenticationException.php
- src/Security/Exception/OAuth2AuthenticationFailedException.php
- tests/Acceptance/DoctrineCredentialsRevokerTest.php
Doctrine ORM v3.0.0 has been released.
https://github.com/doctrine/orm/releases/tag/3.0.0
Upgrade the minimal version of the ORM to v2.14, allow v3.0 as well. This matches the version requirement as used by [doctrine/doctrine-fixtures-bundle](https://github.com/doctrine/DoctrineFixturesBundle/blob/6c3253bfd071b57fac9a5b02cd7b1e5b9803148e/composer.json#L26).
Update the GitHub workflows to test against v2.14, v2.18 and v3.0.
> Support Doctrine ORM 3.0

- src/Security/Authentication/Token/OAuth2Token.php
This - seemingly for no reason - prevents advanced use cases like extending the OAuth2Token with additional custom data.
There's a precedent in that Symfony themselves do not mark any Token classes as final and even extend them themselves.
> Make OAuth2Token non-final

- src/Security/Authenticator/OAuth2Authenticator.php
Hi @chalasr 
This give something more friendly message in case of errors.
From
To
Can consider it
Closes #188
> Add response message when not authenticated

- src/Command/GenerateKeyPairCommand.php
- src/Resources/config/services.php
- tests/Functional/Command/GenerateKeyPairCommandTest.php
- Fix a typo in service decalaration
- Make algorithm as an argument because it was missing in the service definition and cannot be declared
> fix: Fix the command GenerateKeyPair

- src/Resources/config/services.php
The GenerateKeyPairCommand doesn't show up as a command in the console, because of this small typo.
> Fix typo in command registration for GenerateKeyPairCommand

- src/Security/Authenticator/OAuth2Authenticator.php
- tests/Fixtures/FixtureFactory.php
- tests/Integration/ResourceServerTest.php
In `league/server-bundle` version `0.8`, when the client_credentials grant is used, the `sub` claim of the JWT is an empty string, but in version `0.9` is filled with the client ID.
In [Section 5](https://datatracker.ietf.org/doc/html/rfc9068#SecurityConsiderations) of RFC9068, there is a recommendation to prevent the collision between `sub` claim values when the resource owner is either a client or a user.
So when client_id (derived from `aud[0]` claim) and user_id (derived from `sub` claim) are equal, the resource owner must be a client.
Fix #207
> Fix client credentials comparing `oauth_user_id` and `oauth_client_id`

- composer.json
It fixes tests with lowest allowed versions
> Require `league/oauth2-server:^9.2`

- docs/index.md
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/LeagueOAuth2ServerExtension.php
- src/Resources/config/services.php
- tests/Acceptance/CustomPersistenceManagerTest.php
- tests/Acceptance/JwtLeewayConfigurationTest.php
- tests/Integration/AuthorizationServerTest.php
- tests/TestKernel.php
When a jwt token is created on one server and then used on another, there might be a slight time difference in the jwt token timestamp. However the jwt validation is by default set to `PT0S` leeway and rejects the jwt token.
The league/oauth2-server uses lcobucci/jwt for jwt creation and validation. There's an option to set the jwt leeway. See
the constructor of https://github.com/thephpleague/oauth2-server/blob/master/src/AuthorizationValidators/BearerTokenValidator.php
However there is no way to set this value via the oauth2-server-bundle. This PR allows to set this value.
> feat: Add jwt leeway configuration option

- docs/index.md
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/LeagueOAuth2ServerExtension.php
- tests/Unit/ExtensionTest.php
adds a configuration for disabling revocation of refresh token after they were used. this configuration applies to all grant types that will be enabled.
complies with `league/oauth2-server`: https://github.com/thephpleague/oauth2-server/blob/master/src/AuthorizationServer.php#L209-L215
```
league_oauth2_server:
authorization_server:
revoke_refresh_tokens: false
```
> feat: allow configuring revocation of refresh tokens

- src/DependencyInjection/LeagueOAuth2ServerExtension.php
Currently if you happen to not configure DoctrineDBAL, the extension will append the types to the DBAL configuration resulting in an invalid config, which will crash the booting of the Symfony app.
A typical scenario where DBAL may not be configured is if you an an environment with in-memory tests, where DBAL is not used at all.
> fix: Fix the configuration of the extension when DBAL is not configured

- README.md
- composer.json
I think we can move doctrine packages to suggest section.
What do you think? Should we edit the bundle recipe to use `in_memory` as persistence layer?
> [RFC] Move doctrine packages to suggest section

- composer.json
The bundle requires php:^8.1 so this polyfill is useless.
> Remove polyfill requirement
